name: Take a snapshot of transaction data

on:
  # Run every day at 12am
  # schedule:
  #   - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Update dependencies
        run: |
          sudo apt-get update libcurl4-openssl-dev

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Run transaction data script
        run: |
          source("iati_transactions.R")
        shell: Rscript {0}
      - name: Commit new file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
